ApplicationGet/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace ApplicationGet.Controllers
{
    //[Authorize]
    public class AppRolesController : Controller
    {
        private 
            RoleManager<IdentityRole> _roleManager;

        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        //List All the roles created by the user
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            //avoid duplicate role
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }

            return RedirectToAction("Index");
        }
    }
}

ApplicationGet/Controllers/FlightController.cs
using ApplicationGet.Data;
using ApplicationGet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ApplicationGet.Controllers
{
    public class FlightController : Controller
    {
        private readonly ApplicationDBContext _db;
        public FlightController(ApplicationDBContext dB, UserManager<User> userManager)
        {
            _db = dB;
        }

        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            IEnumerable<Flight> objFlightList = _db.Flights.Include(f=>f.FromCity).Include(f=>f.ToCity)
                .Where(f => f.Status == "Active");
            return View(objFlightList);
        }

        [Authorize(Roles = "agent")]
        public IActionResult Overview()
        {
            IEnumerable<Flight> objFlightList = _db.Flights.Include(f => f.FromCity).Include(f => f.ToCity)
                .Where(f => f.Status == "Active");
            return View(objFlightList);
        }

        //GET
        [Authorize(Roles = "agent")]
        public IActionResult Create()
        {
            IEnumerable<City> listOfCities = _db.Cities;
            Flight f = new Flight();
            FlightCities fc = new FlightCities();
            fc.ListOfCities = listOfCities;
            fc.Flight = f;
            return View(fc);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "agent")]
        public IActionResult Create(FlightCities obj)
        {
            if (ModelState.IsValid)
            {
                obj.Flight.FromCity = _db.Cities.Find(obj.Flight.FromCityId);
                obj.Flight.ToCity = _db.Cities.Find(obj.Flight.ToCityId);
                obj.ListOfCities = _db.Cities;

                if (obj.Flight.Date < DateTime.Now)
                {
                    ModelState.AddModelError("CustomError", "Date of flight cannot be in the past.");
                }

                if (obj.Flight.NumberOfSeats <= 0)
                {
                    ModelState.AddModelError("CustomError", "Number of seats cannot be less than or equal to zero.");
                }

                if (obj.Flight.NumberOfLayovers < 0)
                {
                    ModelState.AddModelError("CustomError", "Number of layovers cannot be less than zero.");
                }

                if (obj.Flight.FromCity.Id == obj.Flight.ToCity.Id)
                {
                    ModelState.AddModelError("CustomError", "City from cannot be the same as city to.");
                }

                if (ModelState.ErrorCount > 0)
                    return View(obj);

                _db.Flights.Add(obj.Flight);
                _db.SaveChanges();
                return RedirectToAction("Overview");
            }

            return View(obj);
        }

        //GET
        [Authorize(Roles = "admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            IEnumerable<Flight> objFlightList = _db.Flights.Include(f => f.FromCity).Include(f => f.ToCity).Where(f => f.Id == id);
            Flight f = objFlightList.FirstOrDefault();

            if (f == null)
            {
                return NotFound();
            }

            return View(f);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(Flight fl)
        {
            if (fl.Date < DateTime.Now)
            {
                ModelState.AddModelError("CustomError", "You cannot cancel flight from the past.");

            }

            if (ModelState.ErrorCount > 0)
                return View(fl);

            _db.Flights.Where(x => x.Id == fl.Id).ExecuteUpdate(b => b.SetProperty(u => u.Status, "Cancelled"));
            IEnumerable<Reservation> objReservationList = _db.Reservations.Where(f => f.Flight.Id == fl.Id);

            if (objReservationList != null)
            {
                foreach (Reservation r in objReservationList)
                {
                    _db.Reservations.Where(x => x.UserId == r.UserId && x.Id == r.Id).
                        ExecuteUpdate(b => b.SetProperty(u => u.Status, "Cancelled"));
                }
            }

            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ApplicationGet/Controllers/ReservationController.cs
using ApplicationGet.Data;
using ApplicationGet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ApplicationGet.Controllers
{
    public class ReservationController : Controller
    {
        private 
            ApplicationDBContext _db;

        public ReservationController(ApplicationDBContext dB)
        {
            _db = dB;
        }

        [Authorize(Roles = "agent")]
        public IActionResult Index()
        {
            IEnumerable<Reservation> objReservationtList = _db.Reservations.Include(r => r.User)
                .Include(r => r.Flight).ThenInclude(f => f.FromCity).
                Include(r => r.Flight).ThenInclude(f => f.ToCity).Where(r => r.Status == "Pending");
            return View(objReservationtList);
        }

        //GET
        [Authorize(Roles = "visitor")]
        public IActionResult IndexFlights ([FromQuery(Name = "fromCity.Id")]int? fromCityId, [FromQuery(Name = "toCity.Id")] int? toCityId, bool withoutLayovers)
        {
            FlightsCities fc = new FlightsCities();

            if (fromCityId == null && toCityId == null)
            {
                fc.ListOfFlights = _db.Flights.Include(f => f.FromCity).Include(f => f.ToCity).Where(f => f.Status == "Active" && f.Date >= DateTime.Now);
                fc.ListOfCities = _db.Cities;
                fc.FromCity = new City();
                fc.ToCity = new City();
            }
            else
            {
                if (withoutLayovers) fc.ListOfFlights = _db.Flights.Include(f => f.FromCity).Include(f => f.ToCity).Where(f => f.FromCity.Id == fromCityId && f.ToCity.Id == toCityId && f.NumberOfLayovers == 0 && f.NumberOfSeats > 0 && f.Status == "Active" && f.Date >= DateTime.Now);
                else fc.ListOfFlights = _db.Flights.Include(f => f.FromCity).Include(f => f.ToCity).Where(f => f.FromCity.Id == fromCityId && f.ToCity.Id == toCityId && f.NumberOfSeats > 0 && f.Status == "Active" && f.Date >= DateTime.Now);

                fc.ListOfCities = _db.Cities;
                fc.FromCity = new City();
                fc.ToCity = new City();
            }

            return View(fc);
        }

        [Authorize(Roles = "visitor")]
        public IActionResult IndexUser()
        {
            User user = _db.Users.Find(User.Claims.FirstOrDefault().Value);
            IEnumerable<Reservation> objReservationtList = _db.Reservations.Include(r => r.User).Where(r=>r.User.Id == user.Id)
                .Include(r => r.Flight).ThenInclude(f => f.FromCity).
                Include(r => r.Flight).ThenInclude(f => f.ToCity);

            return View(objReservationtList);
        }

        //GET
        [Authorize(Roles = "visitor")]
        public IActionResult Create(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            IEnumerable<Flight> objFlightList = _db.Flights.Include(f => f.FromCity).Include(f => f.ToCity).Where(f => f.Id == id);
            Flight f = objFlightList.FirstOrDefault();

            if (f == null)
            {
                return NotFound();
            }

            FlightReservation fr = new FlightReservation();
            fr.Reservation = new Reservation();
            fr.Flight = f;

            return View(fr);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "visitor")]
      public IActionResult Create(FlightReservation fr)
        {
            fr.Reservation.User = _db.Users.Find(User.Claims.FirstOrDefault().Value);
            fr.Reservation.Flight = _db.Flights.Find(fr.Flight.Id);
            fr.Reservation.Flight.FromCity = _db.Cities.Find(fr.Reservation.Flight.FromCityId);
            fr.Reservation.Flight.ToCity = _db.Cities.Find(fr.Reservation.Flight.ToCityId);

            if (ModelState.IsValid)
            {
                if (fr.Reservation.NumberOfSeats <= 0)
                {
                    ModelState.AddModelError("CustomError", "Number of seats cannot be less then or equal to zero.");
                }

                if (fr.Reservation.Flight.NumberOfSeats - fr.Reservation.NumberOfSeats < 0)
                {
                    ModelState.AddModelError("CustomError", "There is not enough seats on the flight.");
                }

                if (fr.Reservation.Flight.Date.AddDays(-3) < DateTime.Now.Date)
                {
                    ModelState.AddModelError("CustomError", "Flight is in less than tree days, reservation cannot be made.");
                }

                if (ModelState.ErrorCount > 0)
                    return View();

                IEnumerable<Reservation> listOfReservationsForUser = _db.Reservations.
                    Where(r => r.UserId == fr.Reservation.User.Id);

                if (!listOfReservationsForUser.Any<Reservation>())
                {
                    fr.Reservation.Id = 1;
                }
                else
                {
                    fr.Reservation.Id = listOfReservationsForUser.Count() + 1;
                }

                _db.Reservations.Add(fr.Reservation);
                _db.SaveChanges();

                return RedirectToAction("IndexUser");
            }

             return View(fr);
        }

        //[HttpGet]
        ////[ValidateAntiForgeryToken]
        ////[Authorize(Roles = "visitor")]
        //public Reservation CreateRes([Bind("id", "numberOfSeats")] int id, int numberOfSeats)
        //{
        //    Reservation r = new Reservation();
        //    r.User = _db.Users.Find(User.Claims.FirstOrDefault().Value);
        //    r.Flight = _db.Flights.Find(id);
        //    r.Flight.FromCity = _db.Cities.Find(r.Flight.FromCityId);
        //    r.NumberOfSeats = numberOfSeats;

        //    IEnumerable<Reservation> listOfReservationsForUser = _db.Reservations.Where(res => res.UserId == r.User.Id);
        //    if (!listOfReservationsForUser.Any<Reservation>())
        //    {
        //        r.Id = 1;
        //    }
        //    else
        //    {
        //        r.Id = listOfReservationsForUser.Count() + 1;
        //    }

        //    _db.Reservations.Add(r);
        //    _db.SaveChanges();
        //    return r;
        //}

        //GET
        [Authorize(Roles = "agent")]
        public IActionResult Edit(string? userID, int? id)
        {
            if (id == null || id == 0 || userID == null)
            {
                return NotFound();
            }

            IEnumerable<Reservation> objReservations = _db.Reservations.Include(r => r.Flight).
                ThenInclude(f => f.FromCity).Include(r => r.Flight).
                ThenInclude(f => f.ToCity).Where(x => x.UserId == userID && x.Id == id);
            Reservation r = objReservations.FirstOrDefault();
            
            return View(r);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "agent")]
        public IActionResult Edit(Reservation r)
        {
            if (r.Status != "Pending")
            {
                ModelState.AddModelError("CustomError", "Reservation is not in appropriate status.");
            }

            Flight flight = _db.Flights.Find(r.Flight.Id);

            if (flight.NumberOfSeats - r.NumberOfSeats >= 0)
            {
                flight.NumberOfSeats -= r.NumberOfSeats;
            }
            else
            {
                ModelState.AddModelError("CustomError", "There is not enough seats on the flight.");
            }

            if (ModelState.ErrorCount > 0)
                return View(r);

            r.User = _db.Users.Find(r.UserId);
            r.UserId = r.UserId;
            r.Flight.Id = flight.Id;

            _db.Reservations.Where(x => x.UserId == r.UserId && x.Id == r.Id).
                ExecuteUpdate(b => b.SetProperty(u => u.Status, "Approved"));
            _db.Flights.Where(x => x.Id == r.Flight.Id).
                ExecuteUpdate(b => b.SetProperty(u => u.NumberOfSeats, flight.NumberOfSeats));
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ApplicationGet/Controllers/UserController.cs
using ApplicationGet.Data;
using ApplicationGet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ApplicationGet.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDBContext _db;

        public UserController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return Redirect("Identity/Account/Register?ReturnUrl=%2F");
        }
    }
}

ApplicationGet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApplicationGet</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApplicationGet.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>

                            <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Create user</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Flight" asp-action="Index">Cancel flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Flight" asp-action="Create">Create Flight</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Flight" asp-action="Overview">View Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Reservation" asp-action="Index">Aprove Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Reservation" asp-action="IndexFlights">Make reservation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Reservation" asp-action="IndexUser">View reservations</a>
                        </li>
                        @*  @if (Model.FirstOrDefault().Equals("admin"))
                        {
                        }
                        @if (Model.FirstOrDefault().Equals("agent"))
                        {
                        }
                        @if (Model.FirstOrDefault().Equals("visitor"))
                        {
                        } *@
                     </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ApplicationGet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ApplicationGet/Views/Shared/_navbar.cshtml
@model IList<string>


@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<header>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>

                        <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    @if (Model.FirstOrDefault().Equals("admin"))
                    {
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Flight" asp-action="Index">Cancel flights</a>
                        </li>

                    }
                    @if (Model.FirstOrDefault().Equals("agent"))
                    {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Flight" asp-action="Create">Create Flight</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Flight" asp-action="Overview">View Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Reservation" asp-action="Index">Aprove Reservations</a>
                        </li>

                    }
                    @if (Model.FirstOrDefault().Equals("visitor"))
                    {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Reservation" asp-action="IndexFlights">Make reservation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Reservation" asp-action="IndexUser">View reservations</a>
                        </li>

                    }
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="AppRoles" asp-action="Index">Roles</a>
                    </li>
                </ul>
            </div>
        </div>
        <partial name="_LoginPartial" />
    </nav>

</header>